---
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE,
                      error = TRUE, fig.height = 3,
                      fig.width = 4)

library(tidyverse)

source("../../scripts/ggprob.R")
```

### Read the Boston Marathon Data

```{r}
bm_orig = read_table("../../data/TIM.txt",
                col_types = cols(.default = col_double()))

bm = bm_orig %>% 
  filter(!is.na(`K40-Fin`)) %>% 
  filter(Year < 2013) %>% 
  arrange(Year, BibNum) %>% 
  select(-starts_with("Start"), -HalfMar, -Age2014) %>% 
  mutate(Sex = case_when(
    Gender1F2M == 1 ~ "female",
    Gender1F2M == 2 ~ "male")) %>% 
  mutate(Time = pmap_dbl(select(., starts_with("K")), sum)) %>% 
  mutate(age1 = case_when(
    Age < 35 ~ 18,
    Age >= 80 ~ 80,
    TRUE ~ floor(Age/5)*5),
    age2 = case_when(
      Age < 35 ~ 34,
      TRUE ~ age1 + 4),
    Age_Range = case_when(
      age1 == 80 ~ "80 and older",
      TRUE ~ str_c(age1,"-",age2))) %>% 
  select(-Gender1F2M, -age1, -age2) %>% 
  relocate(BibNum, Year, Sex, Age, Age_Range, Time)
```

### Sample data for women, aged 18-34 in 2010

```{r}
fem_18_34 = bm %>% 
  filter(Sex == "female", Age_Range == "18-34", Year == 2010)

bm_summary = fem_18_34 %>% 
  summarize(averageTime = mean(Time), sdTime = sd(Time), n = n())

bm_summary
```

```{r}
xbar = bm_summary$averageTime
s = bm_summary$sdTime
n = bm_summary$n
```

### Graph the data

```{r}
ggplot(fem_18_34, aes(x = Time)) +
  geom_density(fill = "hotpink") +
  geom_hline(yintercept = 0)
```

### Confidence Interval

```{r}
se = s / sqrt(n)
se

C = 0.95

t_crit = qt(C + (1-C)/2, df = n - 1)
t_crit

moe = t_crit * se
moe

left = xbar - moe
right = xbar + moe

c(left, right)
```

### Using t.test()

```{r}
times = bm %>%
  filter(Sex == "female" & 
           Age_Range == "18-34" & 
           Year == 2010) %>%
  pull(Time)
```

```{r}
t.test(times)
```

### Hypothesis test using t.test()

```{r}
### two-sided test, H_0: mu = 240
t.test(times, mu = 240)

### H_A: mu < 240
t.test(times, mu = 240, alternative = "less")

### H_A: mu > 240
t.test(times, mu = 240, alternative = "greater")
```

## Inference for Difference in Pop means

### Confidence Intervals

```{r}
bm_two_means =  bm %>% 
  filter(Sex == "female", Age_Range == "18-34")


bm_twomeans_summary = bm %>% 
  filter(Sex == "female", Age_Range == "18-34") %>% 
  group_by(Year) %>% 
  summarize(avgTime = mean(Time), sdTime = sd(Time), n = n())

bm_twomeans_summary
```

#### Graphical comparison

```{r}
ggplot(bm_two_means, aes(x = Time, color = as.factor(Year))) +
  geom_density() +
  geom_hline(yintercept = 0)
```

### CI by hand

```{r}
# Extract the values; first by pulling out the length-two vector, then indexing to either the first or second value
# We could've also achieved mu1 with bm_twomeans_summary[1,2] but I find that harder to read

xbar = bm_twomeans_summary$avgTime[1]
ybar = bm_twomeans_summary$avgTime[2]
sx = bm_twomeans_summary$sdTime[1]
sy = bm_twomeans_summary$sdTime[2]
nx = bm_twomeans_summary$n[1]
ny = bm_twomeans_summary$n[2]

```

```{r}
pe = xbar - ybar
pe

### an approximation!
t_crit = 1.96

se1 = sx / sqrt(nx)
se2 = sy / sqrt(ny)
se1
se2

se = sqrt(se1^2 + se2^2)
se

ci = pe + c(-1,1) * t_crit * se
ci
```


### from the notes

```{r}
C = 0.95 # 95% confidence interval
point_estimate = xbar - ybar
se = sqrt(sx^2/nx + sy^2/ny)
W = (sx^2/nx + sy^2/ny)^2 / (sx^4/(nx^2*(nx-1)) + sy^4/(ny^2*(ny-1)))
W

t_crit = qt(0.95 + (1 - 0.95)/2, df = W)
t_crit

moe = qt(0.95 + (1 - 0.95)/2, df = W) * se

left = point_estimate - moe
right = point_estimate + moe

c(left, right)
```

### using t.test()

```{r}
sample_x = bm %>% 
  filter(Sex == "female" &
           Year == 2010 &
           Age_Range == "18-34") %>% 
  pull(Time)

sample_y = bm %>% 
  filter(Sex == "female" &
           Year == 2011 &
           Age_Range == "18-34") %>% 
  pull(Time)


t.test(sample_x, sample_y)
```

### Hypothesis Test p-value graph

```{r}
test_stat = 0.31634

gt(df = W) +
  geom_t_fill(df = W, a = test_stat) +
  geom_t_fill(df = W, b = -test_stat)
```

