---
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE,
                      error = TRUE, fig.height = 3,
                      fig.width = 4)

library(tidyverse)
library(modelr)

source("../../scripts/ggprob.R")
```

### Read in the Chimpanzee Data

```{r}
chimps = read_csv("../../data/chimpanzee.csv")
```

### Summary

```{r}
sum1 = chimps %>% 
  mutate(session_type = case_when(
    partner == "none" ~ "no partner",
    TRUE ~ "partner"
  )) %>% 
  group_by(actor, session_type) %>% 
  summarize(prosocial = sum(prosocial),
            selfish = sum(selfish),
            n = prosocial + selfish,
            pct_prosocial = 100*prosocial/n)
sum1
```

### SE formula check

```{r}
x = 60
n = 90
phat = x/n

se = sqrt(phat * (1-phat) / n)
se
```

### Wald

```{r}

```


### Agresti-coull

```{r}
x = 60
n = 90
conf.level = 0.95

# Calculate AC confidence interval
x_adjusted = x+2 # Added two successes
n_adjusted = n+4 # Added four data points total
phat = x_adjusted/n_adjusted
se = sqrt(phat * (1 - phat)/n_adjusted)  # Changes carry through to p_hat and n_adjusted
moe = qnorm(conf.level + (1 - conf.level)/2) * se
  
left = phat - moe
right = phat + moe
  
c(left, right)
```

### Hypothesis Testing for p

#### Psychic experiment

```{r}
x = 57
n = 200


p_ac = (x+2) / (n+4)
se = sqrt ( p_ac * (1 - p_ac) / ( n+4) )

p_ac
se

z = qnorm(0.975)
z

ci = p_ac + c(-1,1) * z * se
ci
```

### p-value calculation

```{r}
## P(X >= 57) = 1 - P(X <= 56)
p_value = 1 - pbinom(56, 200, 0.25)
p_value
1 / p_value
```

### two-sided alternative

```{r}
gbinom(200, 0.25, scale = TRUE) +
  geom_binom_density(200, 0.25, b = 42, color = "red", scale = TRUE) +
  geom_binom_density(200, 0.25, a = 57, color = "red", scale = TRUE)
```

### Inference for the difference in proportions

> Compare prosocial probabilities with and without a partner

```{r}
chimps %>% 
  filter(actor == "C") %>% 
  mutate(HasAPartner = (partner != "none")) %>% 
  group_by(HasAPartner) %>% 
  summarize(totalProsocial = sum(prosocial),
            totalSelfish = sum(selfish), 
            n = totalProsocial + totalSelfish, 
            p_hat = totalProsocial/n)
```


### Agresti-Coffe CI

```{r}
x1 = 57
n1 = 90
x2 = 17
n2 = 30

p1_ac = (x1 + 1) / (n1 + 2)
p2_ac = (x2 + 1) / (n2 + 2)

p1_ac
p2_ac

pe = p1_ac - p2_ac
se1 = sqrt(p1_ac * (1 - p1_ac) / (n1 +2))
se2 = sqrt(p2_ac * (1 - p2_ac) / (n2 +2))
se1
se2
pe
se = sqrt(se1^2 + se2^2)
se

ci = pe + c(-1,1) * qnorm(0.975) * se
ci
```

### Z-test

```{r}
x1 = 57
n1 = 90
x2 = 17
n2 = 30

p1_hat = x1/n1
p2_hat = x2/n2
p1_hat
p2_hat

pe_ht = p1_hat - p2_hat

### pool into a single sample
p_mean = (x1 + x2) / (n1 + n2)
p_mean

se_ht = sqrt( p_mean * (1-p_mean)/n1 + p_mean * (1 -p_mean) / n2 )
se_ht

z = (pe_ht - 0) / se_ht
z

```

```{r}
gnorm() +
  geom_norm_fill(a = z)

p_value = 1 - pnorm(z)
p_value
```
 
 